### PR TITLE
use method to access queue collection.

### LINKED ISSUE #77: IVAR for QueueInstance
**Describe the bug**
If you ask basket to show you the data before you have gone through the process, `@queue_colleciontion` is not initialized.

This should not happen.

### PR DESCRIPTION
**Pull request by nicholalexander**
* update clear method
* clean up test grouping

closes #77

### CODE REVIEW

File: spec/basket_spec.rb [hunk 1]
```diff
@@ -6,7 +6,6 @@
   end
 
   before do
-    Basket.config
```
Comment (nicholalexander) [inline spec/basket_spec.rb:9]: I thought we needed this and I think we did some time ago but we don't now so i'm removing it.

File: spec/basket_spec.rb [hunk 2]
```diff
@@ -54,6 +53,15 @@
       expect($stdout).to have_received(:puts).with({price: 2345, ticker: :apl})
       expect($stdout).to have_received(:puts).with({price: 345, ticker: :asdf})
     end
+
```
Comment (nicholalexander) [inline spec/basket_spec.rb:56]: just moving this into the describe perform context.
